#!/usr/bin/env bash

hdr=etc/SOURCE_HEADER
lines=($(wc -l $hdr))
lines=${lines[0]}

tmp=/tmp/pre-commit.$$

git diff --cached --name-only | {
    failed=
    while read f; do
        if [ "${f%.java}" != "$f" ];then
            git show ":$f" | head -$lines > $tmp
            if diff $tmp $hdr > /dev/null; then continue; fi
            echo "Missing source header: $f"
            failed=t;
        fi
    done
    test -z $failed
}
